/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Burbot Business Driver
 * OpenAPI spec version: 0.1.0
 */
import type { BusinessModelCreateRequestMetadataJson } from './businessModelCreateRequestMetadataJson';

export interface BusinessModelCreateRequest {
  key: string;
  name: string;
  description?: string | null;
  metadata_json?: BusinessModelCreateRequestMetadataJson;
}
