/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Burbot Business Driver
 * OpenAPI spec version: 0.1.0
 */
import type { BusinessModelMetadataJson } from './businessModelMetadataJson';

/**
 * Top-level logical namespace for a business schema.
 */
export interface BusinessModel {
  id?: number | null;
  key: string;
  name: string;
  description?: string | null;
  metadata_json?: BusinessModelMetadataJson;
  created_at?: string;
}
