/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Burbot Business Driver
 * OpenAPI spec version: 0.1.0
 */
import type { Field } from './field';
import type { SourceLocation } from './sourceLocation';

export interface Entity {
  name: string;
  location: SourceLocation;
  tablename: string;
  fields?: Field[];
}
