/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Burbot Business Driver
 * OpenAPI spec version: 0.1.0
 */
import type { SchemaChangeResponse } from './schemaChangeResponse';

export interface SchemaRegisterResponse {
  changed: boolean;
  revision_id: number | null;
  changes: SchemaChangeResponse[];
  message: string;
}
