/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Burbot Business Driver
 * OpenAPI spec version: 0.1.0
 */
import type { Schema } from './schema';
import type { SchemaRegisterRequestMetadataJson } from './schemaRegisterRequestMetadataJson';

export interface SchemaRegisterRequest {
  schema: Schema;
  reason?: string | null;
  metadata_json?: SchemaRegisterRequestMetadataJson;
}
