/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Burbot Business Driver
 * OpenAPI spec version: 0.1.0
 */

export interface SchemaChangeResponse {
  action: string;
  resource: string;
  entity: string;
  field?: string | null;
}
