/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Burbot Business Driver
 * OpenAPI spec version: 0.1.0
 */
import type { Schema } from './schema';

export interface SchemaDiffRequest {
  schema: Schema;
}
