/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Burbot Business Driver
 * OpenAPI spec version: 0.1.0
 */

export interface SourceLocation {
  line: number;
  column: number;
  end_line: number;
  end_column: number;
}
